version: '3.7'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword  # Указываем пароль для суперпользователя PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app


volumes:
  pgdata: