version: '3.7'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: postgres
      POSTGRES_DB: sxodim
    restart: on-failure
    ports:
      - "5433:5433"
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db



volumes:
  pgdata: